server:
  port: 8443
  servlet:
    session:
      cookie:
        path: /
        http-only: false
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: ./certs/certificate.p12
    key-store-password: revature2022
  http:
    port: 8080
spring:
  devtools:
    livereload:
      enabled: true
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    # database-platform: org.hibernate.dialect.H2Dialect
    # defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://34.122.110.103:5432/postgres?currentSchema=ecommerce
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: revature2022
  h2:
    console.enabled: false
  # jackson:
  #   default-property-inclusion: NON_NULL
  servlet:
    multipart:
      max-file-size: -1